namespace NdflVerification.ReportsContext.Domain.Services.Factories.XsdImplement.Two
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлСвРекв свРеквField;

        private ФайлДокумент[] документField;

        private string идФайлField;

        private string версПрогField;

        private string версФормField;

        /// <remarks/>
        public ФайлСвРекв СвРекв
        {
            get
            {
                return this.свРеквField;
            }
            set
            {
                this.свРеквField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Документ")]
        public ФайлДокумент[] Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвРекв
    {

        private object itemField;

        private string оКТМОField;

        private string отчетГодField;

        private string признакФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвФЛ", typeof(ФайлСвРеквСвФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛ", typeof(ФайлСвРеквСвЮЛ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМО
        {
            get
            {
                return this.оКТМОField;
            }
            set
            {
                this.оКТМОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string ОтчетГод
        {
            get
            {
                return this.отчетГодField;
            }
            set
            {
                this.отчетГодField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПризнакФ
        {
            get
            {
                return this.признакФField;
            }
            set
            {
                this.признакФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвРеквСвФЛ
    {

        private string иННФЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УведВычТип
    {

        private string номерУведField;

        private string датаУведField;

        private string иФНСУведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерУвед
        {
            get
            {
                return this.номерУведField;
            }
            set
            {
                this.номерУведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаУвед
        {
            get
            {
                return this.датаУведField;
            }
            set
            {
                this.датаУведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИФНСУвед
        {
            get
            {
                return this.иФНСУведField;
            }
            set
            {
                this.иФНСУведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СведВыч
    {

        private string кодВычетField;

        private decimal сумВычетField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КодВычет
        {
            get
            {
                return this.кодВычетField;
            }
            set
            {
                this.кодВычетField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумВычет
        {
            get
            {
                return this.сумВычетField;
            }
            set
            {
                this.сумВычетField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИноТип
    {

        private string кодСтрField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр
        {
            get
            {
                return this.кодСтрField;
            }
            set
            {
                this.кодСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get
            {
                return this.адрТекстField;
            }
            set
            {
                this.адрТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвРеквСвЮЛ
    {

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументПодписант подписантField;

        private ФайлДокументСвНА свНАField;

        private ФайлДокументПолучДох получДохField;

        private ФайлДокументСведДох[] сведДохField;

        private string кНДField;

        private string датаДокField;

        private string номСпрField;

        private string отчетГодField;

        private string признакField;

        private string номКоррField;

        private string кодНОField;

        /// <remarks/>
        public ФайлДокументПодписант Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвНА СвНА
        {
            get
            {
                return this.свНАField;
            }
            set
            {
                this.свНАField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументПолучДох ПолучДох
        {
            get
            {
                return this.получДохField;
            }
            set
            {
                this.получДохField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведДох")]
        public ФайлДокументСведДох[] СведДох
        {
            get
            {
                return this.сведДохField;
            }
            set
            {
                this.сведДохField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок
        {
            get
            {
                return this.датаДокField;
            }
            set
            {
                this.датаДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомСпр
        {
            get
            {
                return this.номСпрField;
            }
            set
            {
                this.номСпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string ОтчетГод
        {
            get
            {
                return this.отчетГодField;
            }
            set
            {
                this.отчетГодField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Признак
        {
            get
            {
                return this.признакField;
            }
            set
            {
                this.признакField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомКорр
        {
            get
            {
                return this.номКоррField;
            }
            set
            {
                this.номКоррField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНО
        {
            get
            {
                return this.кодНОField;
            }
            set
            {
                this.кодНОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private ФИОТип фИОField;

        private ФайлДокументПодписантСвПред свПредField;

        private string прПодпField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументПодписантСвПред СвПред
        {
            get
            {
                return this.свПредField;
            }
            set
            {
                this.свПредField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПрПодп
        {
            get
            {
                return this.прПодпField;
            }
            set
            {
                this.прПодпField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантСвПред
    {

        private string наимДокField;

        private string наимОргField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get
            {
                return this.наимДокField;
            }
            set
            {
                this.наимДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }
    }
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНА
    {

        private object itemField;

        private string оКТМОField;

        private string тлфField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвНАФЛ", typeof(ФайлДокументСвНАСвНАФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("СвНАЮЛ", typeof(ФайлДокументСвНАСвНАЮЛ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМО
        {
            get
            {
                return this.оКТМОField;
            }
            set
            {
                this.оКТМОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get
            {
                return this.тлфField;
            }
            set
            {
                this.тлфField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНАСвНАФЛ
    {

        private ФИОТип фИОField;

        private string иННФЛField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвНАСвНАЮЛ
    {

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПолучДох
    {

        private ФИОТип фИОField;

        private ФайлДокументПолучДохУдЛичнФЛ удЛичнФЛField;

        private АдрРФТип адрМЖРФField;

        private АдрИноТип адрИНОField;

        private string иННФЛField;

        private string иННИноField;

        private string статусField;

        private string датаРождField;

        private string граждField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументПолучДохУдЛичнФЛ УдЛичнФЛ
        {
            get
            {
                return this.удЛичнФЛField;
            }
            set
            {
                this.удЛичнФЛField = value;
            }
        }

        /// <remarks/>
        public АдрРФТип АдрМЖРФ
        {
            get
            {
                return this.адрМЖРФField;
            }
            set
            {
                this.адрМЖРФField = value;
            }
        }

        /// <remarks/>
        public АдрИноТип АдрИНО
        {
            get
            {
                return this.адрИНОField;
            }
            set
            {
                this.адрИНОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННИно
        {
            get
            {
                return this.иННИноField;
            }
            set
            {
                this.иННИноField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Статус
        {
            get
            {
                return this.статусField;
            }
            set
            {
                this.статусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаРожд
        {
            get
            {
                return this.датаРождField;
            }
            set
            {
                this.датаРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Гражд
        {
            get
            {
                return this.граждField;
            }
            set
            {
                this.граждField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПолучДохУдЛичнФЛ
    {

        private string кодУдЛичнField;

        private string серНомДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодУдЛичн
        {
            get
            {
                return this.кодУдЛичнField;
            }
            set
            {
                this.кодУдЛичнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get
            {
                return this.серНомДокField;
            }
            set
            {
                this.серНомДокField = value;
            }
        }
    }
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСведДох
    {

        private ФайлДокументСведДохСвСумДох[] дохВычField;

        private ФайлДокументСведДохНалВычССИ налВычССИField;

        private ФайлДокументСведДохСумИтНалПер сумИтНалПерField;

        private string ставкаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("СвСумДох", IsNullable = false)]
        public ФайлДокументСведДохСвСумДох[] ДохВыч
        {
            get
            {
                return this.дохВычField;
            }
            set
            {
                this.дохВычField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСведДохНалВычССИ НалВычССИ
        {
            get
            {
                return this.налВычССИField;
            }
            set
            {
                this.налВычССИField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСведДохСумИтНалПер СумИтНалПер
        {
            get
            {
                return this.сумИтНалПерField;
            }
            set
            {
                this.сумИтНалПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Ставка
        {
            get
            {
                return this.ставкаField;
            }
            set
            {
                this.ставкаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСведДохСвСумДох
    {

        private СведВыч[] свСумВычField;

        private string месяцField;

        private string кодДоходField;

        private decimal сумДоходField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвСумВыч")]
        public СведВыч[] СвСумВыч
        {
            get
            {
                return this.свСумВычField;
            }
            set
            {
                this.свСумВычField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Месяц
        {
            get
            {
                return this.месяцField;
            }
            set
            {
                this.месяцField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КодДоход
        {
            get
            {
                return this.кодДоходField;
            }
            set
            {
                this.кодДоходField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумДоход
        {
            get
            {
                return this.сумДоходField;
            }
            set
            {
                this.сумДоходField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСведДохНалВычССИ
    {

        private СведВыч[] предВычССИField;

        private УведВычТип[] уведСоцВычField;

        private УведВычТип[] уведИмущВычField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПредВычССИ")]
        public СведВыч[] ПредВычССИ
        {
            get
            {
                return this.предВычССИField;
            }
            set
            {
                this.предВычССИField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("УведСоцВыч")]
        public УведВычТип[] УведСоцВыч
        {
            get
            {
                return this.уведСоцВычField;
            }
            set
            {
                this.уведСоцВычField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("УведИмущВыч")]
        public УведВычТип[] УведИмущВыч
        {
            get
            {
                return this.уведИмущВычField;
            }
            set
            {
                this.уведИмущВычField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСведДохСумИтНалПер
    {

        private УведВычТип уведФиксПлатField;

        private decimal сумДохОбщField;

        private decimal налБазаField;

        private decimal налИсчислField;

        private decimal авансПлатФиксField;

        private decimal налУдержField;

        private decimal налПеречислField;

        private decimal налУдержЛишField;

        private decimal налНеУдержField;

        /// <remarks/>
        public УведВычТип УведФиксПлат
        {
            get
            {
                return this.уведФиксПлатField;
            }
            set
            {
                this.уведФиксПлатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумДохОбщ
        {
            get
            {
                return this.сумДохОбщField;
            }
            set
            {
                this.сумДохОбщField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалБаза
        {
            get
            {
                return this.налБазаField;
            }
            set
            {
                this.налБазаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалИсчисл
        {
            get
            {
                return this.налИсчислField;
            }
            set
            {
                this.налИсчислField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal АвансПлатФикс
        {
            get
            {
                return this.авансПлатФиксField;
            }
            set
            {
                this.авансПлатФиксField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалУдерж
        {
            get
            {
                return this.налУдержField;
            }
            set
            {
                this.налУдержField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалПеречисл
        {
            get
            {
                return this.налПеречислField;
            }
            set
            {
                this.налПеречислField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалУдержЛиш
        {
            get
            {
                return this.налУдержЛишField;
            }
            set
            {
                this.налУдержЛишField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НалНеУдерж
        {
            get
            {
                return this.налНеУдержField;
            }
            set
            {
                this.налНеУдержField = value;
            }
        }
    }

}
